# English renderings of the engine's Persian messages (107). EXACT: literal → English.
# PATTERNS: (regex over the Persian message, English format with {0},{1}... groups).
D = "[۰-۹0-9٫.]+"
EXACT = {
 "لغو شد.": "Cancelled.",
 "خطای نامشخص": "Unknown error",
 "دارم گفتار را می‌سازم…": "Generating speech…",
 "گوگل دارد گفتار را می‌سازد…": "Google is generating the speech…",
 "دارم صدا را با زمان‌بندی رونویسی می‌کنم…": "Transcribing with word timing…",
 "دارم موسیقی پس‌زمینه را می‌سازم… (شاید یک دقیقه‌ای طول بکشد)": "Generating the background music… (this can take about a minute)",
 "دارم موسیقی را زیر صدا می‌گذارم…": "Mixing the music under the voice…",
 "دارم بخش‌ها را به هم می‌چسبانم و فایل نهایی را می‌سازم…": "Joining the parts and building the final file…",
 "دارم سرعت گفتار را تنظیم می‌کنم…": "Adjusting the speaking rate…",
 "دانلود موسیقی…": "Downloading the music…",
 "حرکت‌گذاری با مدل محلی…": "Diacritizing with the local model…",
 "مدل محلیِ حرکت‌گذاری دارد آماده می‌شود… (بار اول حدود 70 مگابایت دانلود دارد)": "Preparing the local diacritizer… (about 70 MB is downloaded the first time)",
 "صدای فارسی دارد آماده می‌شود…": "Preparing the Persian voice…",
 "مدل چترباکس دارد از روی دستگاه بارگذاری می‌شود… (یکی دو دقیقه)": "Loading the Chatterbox model from disk… (a minute or two)",
 "فقط همین یک بار: مدل چترباکس (حدود 2 گیگابایت) دانلود می‌شود و از این به بعد روی دستگاه می‌ماند.": "One time only: downloading the Chatterbox model (about 2 GB); it stays on this device afterwards.",
 "فقط همین یک بار: مدل هم‌ترازی واژه‌ها (حدود 1.2 گیگابایت) دانلود می‌شود…": "One time only: downloading the word-alignment model (about 1.2 GB)…",
 "مدل هم‌ترازی آماده است.": "The alignment model is ready.",
 "دارم مدلِ زمان‌بندیِ واژه‌ها را یک بار دانلود می‌کنم (290 مگابایت)…": "Downloading the word-timing model once (290 MB)…",
 "مدلِ زمان‌بندیِ واژه‌ها آماده است.": "The word-timing model is ready.",
 "پیش از ساخت این بخش، حافظهٔ موتور را خالی می‌کنم…": "Freeing the engine's memory before this part…",
 "حافظهٔ چترباکس خالی شد؛ دفعهٔ بعد چند ثانیه بیشتر طول می‌کشد.": "Chatterbox memory was released; the next part takes a few seconds longer.",
 "این بخش دیگر در حافظه نیست؛ یک بار دیگر «تبدیل به گفتار» را بزنید.": "This part is no longer in memory; press “Generate speech” again.",
 "بعضی از بخش‌ها دیگر در حافظه نیستند؛ یک بار دیگر «تبدیل به گفتار» را بزنید.": "Some parts are no longer in memory; press “Generate speech” again.",
 "بخشی نیست که به هم بچسبانیم.": "There are no parts to join.",
 "در این بخش چیزی برای خواندن نیست.": "There is nothing to read in this part.",
 "در این بخش چیزی برای خواندن نیست؛ فقط نشانهٔ مکث دارد.": "There is nothing to read in this part; it only holds a pause marker.",
 "چیزی برای ترمیم نیست؛ این بخش متنی ندارد.": "Nothing to repair; this part has no text.",
 "صدایی ساخته نشد؛ یک بار دیگر امتحان کنید.": "No audio was produced; please try again.",
 "این ابزار کلید API می‌خواهد؛ یک بار در کادر کلید واردش کنید تا ذخیره شود.": "This tool needs an API key; enter it once in the key field and it is saved.",
 "هنوز کلید گوگل ندارید؛ از دکمهٔ «کلیدهای گوگل» یک کلید رایگان وارد کنید.": "No Google key yet; add a free key via “Google keys”.",
 "هنوز کلید گوگل ندارید؛ از دکمهٔ «کلیدهای گوگل» یک کلید وارد کنید.": "No Google key yet; add one via “Google keys”.",
 "هیچ کلید فعالی ثبت نشده.": "No active key is registered.",
 "سهمیهٔ امروزِ همهٔ کلیدهای گوگل تمام شده یا کلیدها معتبر نیستند؛ یک کلید تازه اضافه کنید یا فردا سر بزنید.": "Every Google key is out of quota for today or invalid; add a new key or come back tomorrow.",
 "گوگل به جای صدا جواب خالی داد؛ دوباره امتحان کنید.": "Google returned an empty answer instead of audio; try again.",
 "گوگل: برشِ جملهٔ راهنما قابل اعتماد نبود؛ بدون راهنما می‌سازم…": "Google: the lead-in cut was unreliable; generating without it…",
 "گوگل: مرز جملهٔ راهنما پیدا نشد؛ بدون راهنما می‌سازم…": "Google: the lead-in boundary was not found; generating without it…",
 "هشدار: یک جمله در این بخش درست خوانده نشد؛ بخش را دوباره بسازید یا متنش را ساده‌تر کنید.": "Warning: one sentence in this part was not read properly; regenerate the part or simplify its text.",
 "ساخت موسیقی با لیریا فقط با کلیدِ پولی (پروژه‌ای که صورت‌حساب دارد) کار می‌کند؛ لیریا طرح رایگان ندارد — هر قطعه حدود 8 سنت. ": "Lyria music needs a paid key (a project with billing); there is no free tier — about 8 cents per track. ",
 "لیریا موسیقی‌ای تحویل نداد؛ دوباره امتحان کنید یا حال‌وهوای دیگری بخواهید.": "Lyria did not return music; try again or ask for a different mood.",
 "موسیقی با قالبی رسید که برنامه نمی‌تواند بخواند (WAV خواسته بودیم).": "The music arrived in a format the app cannot read (WAV was requested).",
 "چیزی پیدا نشد؛ سبک یا عبارت دیگری امتحان کنید.": "Nothing found; try another style or search term.",
 "این منبع جست‌وجو ندارد.": "This source has no search.",
 "این قطعه نشانی دانلود ندارد.": "This track has no download address.",
 "این قطعه کمتر از پنج ثانیه است؛ برای پس‌زمینه کوتاه است.": "This track is under five seconds; too short for a background.",
 "این موسیقی دیگر روی دستگاه نیست.": "This music is no longer on this device.",
 "فایل پیدا نشد.": "File not found.",
 "این فایل صوتی تقریباً خالی است.": "This audio file is almost empty.",
 "روی این دیسک جا نیست؛ کمی جا باز کنید و دوباره امتحان کنید.": "There is no room left on this disk; free some space and try again.",
 "این فایل WAV شانزده‌بیتی نیست.": "This WAV file is not 16-bit.",
 "این فایل صوتی به درد نمی‌خورد؛ یک WAV یا MP3 هشت تا پانزده‌ثانیه‌ای با صدای یک نفر انتخاب کنید.": "This audio file will not work; choose an 8–15 s WAV or MP3 of a single speaker.",
 "برای Freesound کلید لازم است: در freesound.org ثبت‌نام کنید و از freesound.org/apiv2/apply کلید بگیرید.": "Freesound needs a key: sign up at freesound.org and get one at freesound.org/apiv2/apply.",
 "برای Jamendo کلید (client_id) لازم است: در devportal.jamendo.com یک اپ بسازید و شناسه‌اش را بردارید.": "Jamendo needs a client_id: create an app at devportal.jamendo.com and copy its ID.",
 "سلام. این فقط یک آزمایش کوتاه است.": "Hello. This is just a short test.",
 "توکن Hugging Face داخل برنامه نیست؛ باید موقع ساختِ برنامه گذاشته می‌شد.": "The Hugging Face token is not inside the app; it had to be added at build time.",
 "موتور چترباکس یکهو بسته شد": "The Chatterbox engine closed unexpectedly",
 "چند برنامهٔ دیگر را ببندید و دوباره امتحان کنید.": "Close a few other apps and try again.",
 "چند برنامهٔ دیگر را ببندید و دوباره امتحان کنید؛ ادامه‌دادن در این وضعیت دستگاه را قفل می‌کند.": "Close a few other apps and try again; continuing like this would freeze the device.",
 "اگر برنامه‌های دیگر را ببندید، کمک می‌کند.": "Closing other apps helps.",
 "همین بخش را دوباره بسازید.": "Regenerate this part.",
 "برای اینکه خروجی خراب نشود، این بخش را کامل از نو بسازید.": "To avoid a damaged result, regenerate this whole part.",
 "اینترنت را چک کنید و این بخش را دستی دوباره بسازید.": "Check the internet connection and regenerate this part manually.",
 "این بخش خودبه‌خود ترمیم و از نو ساخته شد.": "This part was repaired and rebuilt automatically.",
 "یک ناسازگاری داخلی پیدا شد؛ این بخش خودکار ترمیم می‌شود…": "An internal inconsistency was found; repairing this part automatically…",
 "تغییر سرعت ممکن نشد؛ با سرعت عادی ساخته شد.": "Rate change was not possible; generated at normal speed.",
 "متن یک‌نفس و طبیعی خوانده شد و مکث‌ها با هم‌ترازی درست سر جای نشانه‌ها نشستند.": "The text was read in one natural take and the pauses were placed exactly at the markers by alignment.",
 "تکهٔ کوتاه را همراه متن کناری‌اش یک‌جا خواندیم و بعد با هم‌ترازی جدایش کردیم.": "The short piece was read together with its neighbouring text and separated by alignment.",
 "برشِ متنِ کناری قابل اعتماد نبود؛ بدون متن کناری می‌سازیم…": "The context cut was unreliable; generating without context…",
 "این خطا در گزارش برنامه ثبت شد؛ لطفاً فایل گزارش (ava.log) را بفرستید.": "This error was written to the app log; please send the log file (ava.log).",
 "\nاین خطا در گزارش برنامه ثبت شد؛ اگر باز هم پیش آمد، فایل گزارش (ava.log) را بفرستید.": "\nThis error was written to the app log; if it happens again, send the log file (ava.log).",
 "قالب صدای موتور را نمی‌شناسم (نمونه‌ها 16بیتی نیستند).": "Unrecognised engine audio format (samples are not 16-bit).",
 "موتور صداهای سبک نتوانست این بخش را بسازد. دلیل: ": "The light-voice engine could not build this part. Reason: ",
 "موتور صداهای سبک خطا داد:\n": "The light-voice engine reported an error:\n",
 "گوگل این درخواست را قبول نکرد: ": "Google rejected this request: ",
 "پاسخ گوگل: ": "Google's answer: ",
 "موسیقی: ": "Music: ",
 " — یک بار دیگر امتحان کنید.": " — please try again.",
 " — ناتمام ماند": " — incomplete",
 "این فایل صوتی به درد نمی‌خورد؛": "This audio file will not work;",
 "چترباکس روی این دستگاه اجرا نمی‌شود؛ دست‌کم 8 گیگابایت رم می‌خواهد ": "Chatterbox cannot run on this device; it needs at least 8 GB of RAM ",
 "حافظهٔ این دستگاه برای هم‌ترازیِ واژه‌به‌واژه کافی نیست": "This device does not have enough memory for word-level alignment",
 "نمونهٔ صدایی که انتخاب کرده‌اید پیدا نشد: ": "The selected voice sample was not found: ",
 "کلید Fish Audio ثبت نشده؛ از fish.audio/app/api-keys یک کلید رایگان بگیرید و در «کلید Fish Audio» وارد کنید.": "No Fish Audio key; get a free one at fish.audio/app/api-keys and paste it in the Fish Audio key field.",
 "Fish Audio دارد گفتار را می‌سازد…": "Fish Audio is generating the speech…",
 "Fish Audio: ساختِ صدای کلون از نمونه (فقط بار اول برای هر نمونه)…": "Fish Audio: cloning the clip into a voice (first time only per clip)…",
 "Fish Audio: طراحی صدا…": "Fish Audio: designing the voice…",
 "جملهٔ جاافتاده را جداگانه می‌سازم و سرِ جایش می‌گذارم…": "Generating the missing sentence on its own and splicing it into place…",
 "صدا/تنظیمات این بخش عوض شده؛ فقط جمله‌های انتخاب‌شده با صدای تازه ساخته می‌شوند.": "The voice/settings of this part changed; only the selected sentences are rebuilt with the new voice.",
 "گوگل از این شبکه درخواست نمی‌پذیرد (خطای 403 یا قطع اتصال). این مشکل از کلیدها نیست و هیچ کلیدی نامعتبر نشد؛ فیلترشکن یا اتصال اینترنت را عوض کنید و دوباره امتحان کنید.": "Google is not accepting requests from this network (error 403 or a dropped connection). This is not a key problem and no key was marked invalid; change the VPN or internet connection and try again.",
 "گوگل می‌گوید این سرویس در موقعیتِ فعلیِ شبکه در دسترس نیست. این مشکل از کلیدها نیست و هیچ کلیدی نامعتبر نشد؛ با فیلترشکنی که مقصدش کشورِ دیگری است امتحان کنید.": "Google says the service is not available from the network's current location. This is not a key problem and no key was marked invalid; try a VPN exiting in another country.",
 "به گوگل نرسیدیم: اینترنت وصل نیست، یا — اگر در کشوری هستید که گوگل را محدود کرده، مثل ایران — فیلترشکن وصل نیست. اگر فیلترشکن روشن است، آن را روی حالتِ TUN بگذارید.": "Could not reach Google: the internet is not connected, or — if you are in a country that restricts Google, such as Iran — the VPN is not connected. If the VPN is on, put it in TUN mode.",
 "گوگل این سرویس را برای کشورِ فعلیِ فیلترشکن ارائه نمی‌دهد؛ سروری در اروپا یا آمریکای شمالی انتخاب کنید.": "Google does not offer this service for the VPN's current country; choose a server in Europe or North America.",
 "گوگل نشانیِ فعلیِ فیلترشکن را مسدود کرده است؛ سرور یا کشورِ دیگری انتخاب کنید، یا فیلترشکن را روی حالتِ TUN بگذارید.": "Google has blocked the VPN's current address; choose another server or country, or put the VPN in TUN mode.",
 "جراحیِ جمله ممکن نشد؛ کل این بخش دوباره ساخته می‌شود.": "Sentence surgery was not possible; the whole part is being rebuilt.",
 "نقشهٔ جمله‌های این بخش قابل‌اعتماد نیست؛ ویرایش بعدی از روی رونویسیِ تازه انجام می‌شود، و اگر نشد کل بخش دوباره ساخته می‌شود.": "This part's sentence map is not trustworthy; the next edit will work from a fresh transcript, and rebuild the whole part if that fails.",
 "مرز جمله‌های این بخش پیدا نشد؛ ویرایشِ جزئی روی آن کل بخش را دوباره می‌سازد.": "This part's sentence boundaries could not be found; a partial edit will rebuild the whole part.",
 "Fish Audio: کلید پذیرفته نشد (401). کلید را دوباره بررسی کنید.": "Fish Audio: key rejected (401). Check the key.",
 "Fish Audio: اعتبار حساب تمام شده (402). برای مدل پولی باید شارژ کنید؛ مدل رایگان s2.1-pro-free را انتخاب کنید.": "Fish Audio: out of credit (402). Top up for the paid model, or pick the free s2.1-pro-free.",
 "Fish Audio: برشِ جملهٔ راهنما قابل اعتماد نبود؛ بدون راهنما می‌سازم…": "Fish Audio: the lead-in cut was unreliable; generating without it…",
 "مدل S1 چندگوینده را پشتیبانی نمی‌کند؛ یکی از مدل‌های S2 را انتخاب کنید.": "S1 has no multi-speaker mode; pick an S2 model.",
    'روی خطِ زمان چیزی برای ساختن نیست.': 'There is nothing on the timeline to build.',
    'دارم کلیپ\u200cهای خطِ زمان را کنارِ هم می\u200cگذارم…': "Placing the timeline's clips…",
    'ساختنِ فایل از خطِ زمان': 'building the file from the timeline',
    # 179 · Chatterbox memory: flushed and carried on
    "مدل چترباکس دوباره بارگذاری می‌شود…": "Reloading the Chatterbox model…",
    "حافظهٔ چترباکس خالی شد؛ کار از همین‌جا ادامه دارد…": "Chatterbox memory was flushed; the work carries on from here…",
    "حافظهٔ چترباکس خالی شد؛ مدل دوباره بارگذاری می‌شود و کار از همین‌جا ادامه دارد…": "Chatterbox memory was flushed; the model is reloading and the work carries on from here…",
    "حافظهٔ پردازندهٔ گرافیکی برای چترباکس کم آمد؛ حافظه را خالی می‌کنم و همین تکه را دوباره می‌سازم…": "The graphics memory ran short for Chatterbox; flushing it and making this piece again…",
    "حافظهٔ پردازندهٔ گرافیکی برای چترباکس کم آمد؛ حافظه را خالی می‌کنم و این تکه را در دو نیمه می‌سازم…": "The graphics memory ran short for Chatterbox; flushing it and making this piece in two halves…",
    "حافظهٔ آزاد این دستگاه تمام شد؛ چترباکس را نگه داشتم تا دستگاه قفل نکند و همین تکه را دوباره می‌سازم…": "This computer ran out of free memory; Chatterbox was stopped so it would not freeze, and this piece is made again…",
}
PATTERNS = [
 (r"^مدلِ زمان‌بندیِ واژه‌ها: (" + D + ")%$", "Word-timing model: {0}%"),
 (r"^دارم گفتار را می‌سازم… بخش (\S+) از (\S+)$", "Generating speech… part {0} of {1}"),
 (r"^دارم گفتار را می‌سازم… تکهٔ (\S+) از (\S+)$", "Generating speech… piece {0} of {1}"),
 (r"^دانلود (.+?)… (\S+)%$", "Downloading {0}… {1}%"),
 (r"^دانلود (.+?)…$", "Downloading {0}…"),
 (r"^حرکت‌گذاری با (.+?)… تکهٔ (\S+) از (\S+)$", "Diacritizing with {0}… piece {1} of {2}"),
 (r"^چسباندن بخش (\S+)$", "Joining part {0}"),
 (r"^گوگل: صدا دارد می‌رسد… (\S+) ثانیه$", "Google: audio arriving… {0} s"),
 (r"^گوگل: (\S+) ثانیه صدا رسید(.*)$", "Google: {0} s of audio received{1}"),
 (r"^گوگل: (\S+) جمله را همراه جمله‌های کناری‌اش دوباره می‌سازد…$", "Google: regenerating {0} sentence(s) with their neighbours…"),
 (r"^گوگل جمله‌ای را جا انداخت — برداشت دوباره \((\S+)\)…$", "Google skipped a sentence — retake ({0})…"),
 (r"^گوگل از مسیر (\S+) جواب نداد \((\S+) ثانیه\)؛ مسیر دیگر را امتحان می‌کنم…$", "Google did not answer via {0} ({1} s); trying the other route…"),
 (r"^گوگل جواب نداد \((\S+) ثانیه از هر دو مسیر صبر کردیم\)\. اینترنت یا وی‌پی‌ان را چک کنید و دوباره بزنید\.$", "Google did not answer ({0} s on both routes). Check the internet/VPN and try again."),
 (r"^(.+?): اتصال برقرار نشد \((.+?)\) — تلاش (\S+) از 3…$", "{0}: connection failed ({1}) — attempt {2} of 3…"),
 (r"^(.+?): سرور گوگل موقتاً خطا داد \((\S+)\) — تلاش (\S+) از 3…$", "{0}: Google's server gave a temporary error ({1}) — attempt {2} of 3…"),
 (r"^(.+?): این کلید را قبول نکرد؛ می‌رویم سراغ کلید بعدی…$", "{0}: this key was rejected; moving to the next key…"),
 (r"^(.+?): سهمیهٔ امروزِ این کلید ته کشید؛ می‌رویم سراغ کلید بعدی…$", "{0}: this key's daily quota is used up; moving to the next key…"),
 (r"^(.+?): به سقف درخواست در دقیقه خوردیم — 20 ثانیه صبر می‌کنیم…$", "{0}: per-minute request limit reached — waiting 20 s…"),
 (r"^(.+?): با هیچ‌کدام از کلیدها جواب نگرفتیم — (.*)$", "{0}: no key succeeded — {1}"),
 (r"^جست‌وجوی موسیقی در (\S+)… صفحهٔ (\S+)$", "Searching music on {0}… page {1}"),
 (r"^دانلود نشد \(HTTP (\d+)\)\.$", "Download failed (HTTP {0})."),
 (r"^جواب رسید: (\S+) ثانیه صدا، در (\S+) ثانیه \((.+?)\)$", "Answer received: {0} s of audio in {1} s ({2})"),
 (r"^(.+?) — بعد از (\S+) ثانیه$", "{0} — after {1} s"),
 (r"^حافظهٔ چترباکس خالی شد \((\S+) گیگابایت آزاد شد\)؛ دفعهٔ بعد چند ثانیه بیشتر طول می‌کشد\.$", "Chatterbox memory was released ({0} GB freed); the next part takes a few seconds longer."),
 (r"^چترباکس به (\S+) گیگابایت حافظه رسید و برای اینکه دستگاه قفل نکند متوقف شد؛ دفعهٔ بعد یک نسخهٔ تازه از آن ساخته می‌شود — همین بخش را دوباره بسازید\.$", "Chatterbox reached {0} GB of memory and was stopped so the Mac would not freeze; a fresh copy starts next time — generate this part again."),
 (r"^حافظهٔ آزاد برای چترباکس کم است \(فقط (\S+) مگابایت\)\. (.*)$", "Free memory is low for Chatterbox (only {0} MB). {1}"),
 (r"^هشدار: حافظهٔ آزاد کم است \((\S+) گیگابایت\)؛ ممکن است کار کند پیش برود\. (.*)$", "Warning: free memory is low ({0} GB); things may go slowly. Closing other programs helps."),
 (r"^ساخت دوبارهٔ (\S+) تکهٔ تغییرکرده…$", "Regenerating {0} changed piece(s)…"),
 (r"^جراحی واژه‌ای: فقط «(.+?)» دوباره ساخته می‌شود…$", "Word surgery: only “{0}” is regenerated…"),
 (r"^یک‌نفس خواندن جواب نداد \((.+?)\)؛ تکه‌تکه می‌سازیم\.$", "One-take reading failed ({0}); generating piece by piece."),
 (r"^هم‌ترازی واژه‌ای جواب نداد \((.+?)\)؛ کل تکه دوباره ساخته می‌شود\.$", "Word alignment failed ({0}); regenerating the whole piece."),
 (r"^تنظیمات صدای (\S+) خراب بود؛ دارم درستش می‌کنم…$", "The settings of voice {0} were corrupt; fixing…"),
 (r"^فایل (\S+) روی دستگاه خراب بود؛ دوباره دانلودش می‌کنم…$", "The file {0} on this device was corrupt; downloading it again…"),
 (r"^موتور صداهای سبک با کد (\S+) بسته شد \(خطای داخلی\)\.$", "The light-voice engine exited with code {0} (internal error)."),
 (r"^این قالب صوتی را نمی‌توانم بخوانم \((.+?)\)؛ WAV، MP3، OGG یا FLAC بدهید\.$", "Cannot read this audio format ({0}); use WAV, MP3, OGG or FLAC."),
 (r"^این قالب صوتی را نمی‌توانم بخوانم \((.+?)\)؛ WAV، MP3، M4A، OGG یا FLAC بدهید\.$", "Cannot read this audio format ({0}); use WAV, MP3, M4A, OGG or FLAC."),
 (r"^\(این دستگاه (\S+) گیگابایت دارد\)\. به‌جایش از صداهای سبک — مانا، ژیرو یا امیر — استفاده کنید\.$", "(this device has {0} GB). Use the light voices — Mana, Gyro or Amir — instead."),
 (r"^چترباکس روی این دستگاه اجرا نمی‌شود؛ دست‌کم 8 گیگابایت رم می‌خواهد (.*)$", "Chatterbox cannot run on this device; it needs at least 8 GB of RAM {0}"),
 (r"^نمونهٔ صدایی که انتخاب کرده‌اید پیدا نشد: (.*)$", "The selected voice sample was not found: {0}"),
 (r"^موسیقی: «(.+?)» از (.*?) — (.+?) — (.*)$", "Music: “{0}” by {1} — {2} — {3}"),
 (r"^Fish Audio جمله‌ای را جا انداخت — برداشت دوباره \((\S+)\)…$", "Fish Audio skipped a sentence — retake ({0})…"),
 (r"^Fish Audio \((\d+)\): (.*)$", "Fish Audio ({0}): {1}"),
 (r"^برشِ جمله جا نیفتاد؛ برداشت دوباره \((\S+)\)…$", "The cut did not land cleanly; taking it again ({0})…"),
 (r"^(\S+) خط دیگر هم باید ساخته شود .*$", "{0} more line(s) must be made; they keep their own voice."),
 (r"^(\S+) بخشِ حذف‌شده از صدا برداشته شد.*$", "{0} deleted stretch(es) removed from the audio; nothing regenerated."),
 (r"^(\S+) بخش با صداهای متفاوت ساخته می‌شود.*$", "{0} runs with different voices will be made; unselected lines keep their own voice."),
 (r"^Fish Audio ASR \((\d+)\): (.*)$", "Fish Audio ASR ({0}): {1}"),
 # 179 · Chatterbox memory: flushed and carried on
 (r"^چترباکس به (\S+) گیگابایت حافظه رسید؛ حافظه را خالی می‌کنم و همین تکه را دوباره می‌سازم…$", "Chatterbox reached {0} GB of memory; flushing it and making this piece again…"),
 (r"^چترباکس به (\S+) گیگابایت حافظه رسید؛ حافظه را خالی می‌کنم و این تکه را در دو نیمه می‌سازم…$", "Chatterbox reached {0} GB of memory; flushing it and making this piece in two halves…"),
 (r"^حافظهٔ آزاد این دستگاه کم است \((\S+) گیگابایت\)؛ منتظرم برنامه‌های دیگر حافظه را پس بدهند — اگر می‌توانید چندتایی را ببندید…$", "This computer is low on free memory ({0} GB); waiting for other programs to give some back — close a few if you can…"),
 (r"^حافظهٔ آزاد این دستگاه برای چترباکس کافی نیست \((\S+) گیگابایت آزاد است\)\. چند برنامهٔ دیگر را ببندید و دوباره بسازید\.$", "This computer does not have enough free memory for Chatterbox ({0} GB free). Close a few programs and generate again."),
 (r"^این تکه حتی در دو نیمه هم در حافظهٔ این دستگاه جا نشد \(چترباکس به (\S+) گیگابایت رسید\)\. برنامه‌های دیگر را ببندید یا این خط را کوتاه‌تر کنید و دوباره بسازید\.$", "This piece did not fit in this computer's memory even in two halves (Chatterbox reached {0} GB). Close other programs or shorten this line, then generate again."),
]

# 182 · safe saves, the recovery copy, import limits
EXACT.update({
 "نسخهٔ بازیابی پیدا نشد.": "The recovery copy was not found.",
})
PATTERNS += [
 (r"^روی این دیسک جا نیست: این کار حدود (" + D + r") مگابایت جا لازم دارد و فقط (" + D + r") مگابایت آزاد است\. کمی جا باز کنید یا جای دیگری را انتخاب کنید\.$",
  "Not enough room on this disk: this needs about {0} MB and only {1} MB is free. Free up some space or choose another place."),
 (r"^«(.+)» (" + D + r") مگابایت است؛ یک فایلِ صوتی حداکثر 250 مگابایت می‌تواند باشد\.$", "“{0}” is {1} MB; an audio file can be at most 250 MB."),
 (r"^«(.+)» (" + D + r") دقیقه است؛ یک فایلِ صوتی حداکثر 60 دقیقه می‌تواند باشد\.$", "“{0}” is {1} minutes long; an audio file can be at most 60 minutes."),
]
