"""155 · PROTECT — run by the cloud build BEFORE PyInstaller (never shipped, never imported).

  1. STAMP   the copy id (COPY_ID env, e.g. L-02; default "dev") into the build.
  2. SEAL    the bundled keys (builtin_keys.json, token.txt) into _vault.py, obfuscated,
             then delete the plain files so they never reach the app.
  3. MINIFY  the interface scripts (terser via npx, if available — skipped with a notice if not).
  4. COMPILE the app's own Python (app, engines, licensing, en_strings, _vault) to native
             machine code with Cython, then delete their .py / .c sources from the workspace.
  5. LIST    the libraries those modules import (_hidden.json) — PyInstaller cannot see
             imports inside compiled modules, so build.spec reads this list.
Honest scope: this makes the code unreadable and the activation hard to patch out; it does
not make a determined reverse-engineer's job impossible. Copies stay few, expiring, traceable.
"""
import ast, base64, json, os, re, secrets, shutil, subprocess, sys, glob
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
MODULES = ["app", "engines", "licensing", "en_strings", "_vault"]
say = lambda *a: print("[protect]", *a, flush=True)

# ---- 1 · stamp
copy_id = (os.environ.get("COPY_ID") or "dev").strip()
if copy_id != "dev" and not re.fullmatch(r"[A-Z]{1,3}-\d{1,4}", copy_id):
    sys.exit(f"[protect] COPY_ID must be an opaque id like L-02 (never a name); got {copy_id!r}")

# ---- 2 · seal
vault = {}
if os.path.exists("builtin_keys.json"):
    vault.update({k: v for k, v in (json.load(open("builtin_keys.json", encoding="utf-8")) or {}).items() if v})
if os.path.exists("token.txt"):
    t = open("token.txt", encoding="utf-8").read().strip()
    if t and "PASTE" not in t.upper():
        vault["hf_token"] = t
key = secrets.token_bytes(32)
enc = {k: base64.b64encode(bytes(b ^ key[i % len(key)] for i, b in enumerate(v.encode("utf-8")))).decode() for k, v in vault.items()}
open("_vault.py", "w", encoding="utf-8").write(
    "# generated by tools/protect.py — compiled to native code, never shipped as source\n"
    f"COPY_ID = {copy_id!r}\nBUILT = {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%MZ')!r}\n"
    f"_K = bytes.fromhex({key.hex()!r})\n_S = {enc!r}\n\n"
    "def get(name):\n    import base64\n    d = _S.get(name)\n    if not d:\n        return ''\n"
    "    b = base64.b64decode(d)\n    return bytes(x ^ _K[i % len(_K)] for i, x in enumerate(b)).decode('utf-8')\n")
for f in ("builtin_keys.json", "token.txt"):
    if os.path.exists(f):
        os.remove(f)
say(f"stamped copy {copy_id}; sealed {len(vault)} key(s): {sorted(vault)}; plain key files removed")

# ---- 3 · minify the interface scripts (inline <script> blocks without src)
npx = shutil.which("npx")
if npx and os.environ.get("PROTECT_NO_MINIFY") != "1":
    for html in sorted(glob.glob("ui/*.html")):
        src = open(html, encoding="utf-8").read(); out, pos, n = [], 0, 0
        for m in re.finditer(r"<script>(.*?)</script>", src, re.S):
            body = m.group(1)
            if len(body.strip()) < 200:
                continue
            r = subprocess.run([npx, "--yes", "terser@5", "--compress", "--mangle", "--ecma", "2020"],
                               input=body, capture_output=True, text=True, encoding="utf-8")
            if r.returncode != 0 or not r.stdout.strip():
                say(f"NOTICE: minifier unavailable or failed on {html} — this file's scripts stay readable ({r.stderr[:160].strip()})")
                continue
            out.append(src[pos:m.start(1)]); out.append(r.stdout.strip().replace("</script", "<\\/script")); pos = m.end(1); n += 1
        out.append(src[pos:])
        open(html, "w", encoding="utf-8").write("".join(out))
        say(f"minified {n} script block(s) in {html}")
else:
    say("NOTICE: npx not found (or PROTECT_NO_MINIFY=1) — interface scripts left readable")

# ---- 5 (before 4, while the sources still exist) · the libraries the compiled modules import
hidden = set(MODULES)
for mod in MODULES:
    for node in ast.walk(ast.parse(open(mod + ".py", encoding="utf-8").read())):
        if isinstance(node, ast.Import):
            hidden.update(a.name for a in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
            hidden.add(node.module)
json.dump(sorted(hidden), open("_hidden.json", "w"), indent=0)
say(f"{len(hidden)} imports listed for PyInstaller (_hidden.json)")

# the build number, written out before engines.py disappears (the workflow names files with it)
bm = re.search(r"^BUILD = (\d+)", open("engines.py", encoding="utf-8").read(), re.M)
open("BUILD_NUMBER", "w").write(bm.group(1) if bm else "0")
say(f"build number {bm.group(1) if bm else '?'} written to BUILD_NUMBER")

# ---- 4 · compile to native code, then remove the sources
r = subprocess.run([sys.executable, "-m", "Cython.Build.Cythonize", "-i", "-3", "-q", "-j", str(max(2, os.cpu_count() or 2)), *[m + ".py" for m in MODULES]])   # all cores: several times faster
if r.returncode != 0:
    sys.exit("[protect] Cython failed — not building an unprotected app")
for mod in MODULES:
    built = [f for f in os.listdir(".") if f.startswith(mod + ".") and f.endswith((".so", ".pyd"))]
    if not built:
        sys.exit(f"[protect] {mod} did not compile")
    for leftover in (mod + ".py", mod + ".c"):
        if os.path.exists(leftover):
            os.remove(leftover)
shutil.rmtree("build", ignore_errors=True)
say("compiled to native code: " + ", ".join(sorted(f for f in os.listdir(".") if f.endswith((".so", ".pyd")))))
say("sources removed: " + ", ".join(m + ".py" for m in MODULES))
